### PR TITLE
fix: remove references to old schema fields

### LINKED ISSUE #511: "Publisher:" and "Published:" values are empty on pathway details pages
"Publisher:" and "Published:" labels appear in the upper blue header of each pathway details page, but the associated values do not. Presumably, they should show the same values the appear on the pathway cards on the search page?

Image
Image

### PR DESCRIPTION
**Pull request by jdhoffa**
This handles the immediate bug of "Publisher:" and "Published:" values being empty on the Scenario Details page.
The broader challenge of enabling type-checking and dealing with the root of this problem more holistically by handling all `typecheck` failures is being handled concurrently (see #514 and related PRs).

Closes #511

### CODE REVIEW

File: src/utils/searchUtils.ts [hunk 1]
```diff
@@ -254,8 +254,8 @@ export const filterPathways = (
         ...pathway.geography.map((s) => geographyLabel(s)),
         ...pathway.sectors.map((s) => s.name),
         ...pathway.metric,
-        pathway.publisher,
-        pathway.publicationYear,
+        pathway.publication.publisher.full,
```
Comment (AlexAxthelm) [inline src/utils/searchUtils.ts:257]: NB: Do we also want to be able to search on `publisher.short`? (IEA, instead of International Energy Agency)?

**Review by AlexAxthelm — DISMISSED** [review]

File: src/utils/searchUtils.ts (hunk 1 above)
Comment (jdhoffa) [reply src/utils/searchUtils.ts:257]: Yeah, that's probably a good idea

**Review by AlexAxthelm — APPROVED** [review]
